In [2]:
import pandas as pd
import numpy as np
import ase
from ase.io import read
from io import StringIO
import json
import torch


In [3]:
with open("elements.json") as file:
    elements = json.load(file)

In [8]:
data = pd.read_csv("train.csv")
print(len(data))
cif1 = data['cif'][10]
lines = cif1.strip().split('\n')

lengths = np.array([line.split()[1] for line in lines[3:6]], dtype=float)
angles = np.array([line.split()[1] for line in lines[6:9]], dtype=float)
atom_types = [line.split()[0] for line in lines[26:]]
atom_types

11356


['Ir', 'Al', 'N', 'N', 'O']

In [61]:
data = pd.read_csv("perov5/test.csv")
cif1 = StringIO(data['cif'][10])
structure = read(cif1, format="cif")

lengths = np.array(structure.get_cell().lengths(), dtype=float)
angles = np.array(structure.get_cell().angles(), dtype=float)
atom_types = [elements[i] for i in structure.get_chemical_symbols()]
num_atoms = len(atom_types)
frac_cords = np.array(structure.get_scaled_positions(), dtype=float)

In [96]:
def getdb(dataset_csv):
    data = pd.read_csv(dataset_csv, skipinitialspace=True)
    db = []
    for i in range(200):
        cif = StringIO(data['cif'][i])
        structure = read(cif, format="cif")

        # target (y)
        prop = data['energy'][i]

        # fractional coordinates
        frac_cords = np.array(structure.get_scaled_positions(), dtype=float)

        # atom types and number of atoms
        atom_types = [elements[i] for i in structure.get_chemical_symbols()]
        num_atoms = len(atom_types)

        # Angles
        angles = np.array(structure.get_cell().angles(), dtype=float)

        # Lengths
        lengths = np.array(structure.get_cell().lengths(), dtype=float)

        # data_point = [x=torch.tensor(frac_cords, dtype=torch.float32),
        #                   frac_coords=torch.tensor(frac_cords, dtype=torch.float32),
        #                   atom_types=torch.tensor(atom_types, dtype=torch.int),
        #                   lengths=torch.tensor(lengths, dtype=torch.float32).view(1, -1),
        #                   angles=torch.tensor(angles, dtype=torch.float32).view(1, -1),
        #                   num_atoms=torch.tensor(num_atoms),
        #                   y=torch.tensor(prop, dtype=torch.float32).view(1, -1)]

        db.append(angles)
    return db


getdb("../data/GSFE2/dataset.csv.txt")

[array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
 array([90., 90., 90.]),
